apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: kube-state-metrics
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: v2.16.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-state-metrics
        app.kubernetes.io/version: v2.16.0
    spec:
      serviceAccountName: kube-state-metrics
      containers:
      - name: kube-state-metrics
        image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.16.0
        args:
        - --port=8080
        - --telemetry-port=8081
        - --resources=pods,nodes,services,deployments,replicasets,statefulsets,daemonsets,configmaps,secrets,namespaces,resourcequotas,limitranges,persistentvolumeclaims,persistentvolumes,storageclasses,horizontalpodautoscalers,verticalpodautoscalers,cronjobs,jobs,leases,endpointslices,ingresses,networkpolicies,priorityclasses,runtimeclasses,poddisruptionbudgets,clusterroles,clusterrolebindings,roles,rolebindings,apiservices,certificatesigningrequests,storageclasses,volumeattachments,csinodes,customresourcedefinitions,mutatingwebhookconfigurations,validatingwebhookconfigurations
        ports:
        - name: metrics
          containerPort: 8080
        - name: telemetry
          containerPort: 8081
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 5
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 50m
            memory: 75Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
