apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-state-metrics

resources:
- namespace.yaml
- service-account.yaml
- deployment.yaml
- service.yaml

commonLabels:
  app.kubernetes.io/name: kube-state-metrics
  app.kubernetes.io/version: v2.16.0
  app.kubernetes.io/component: metrics
  app.kubernetes.io/part-of: kube-state-metrics
