services:
  db:
    image: mysql:8.4.6
    restart: always
    environment:
      MYSQL_DATABASE: sampledb
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data:
    driver: local
