version: '3.8'
services:
  shard0:
    image: mysql:8.0
    container_name: mysql-shard-0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - "3307:3306"
    volumes:
      - shard0-data:/var/lib/mysql

  shard1:
    image: mysql:8.0
    container_name: mysql-shard-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - "3308:3306"
    volumes:
      - shard1-data:/var/lib/mysql

  shard2:
    image: mysql:8.0
    container_name: mysql-shard-2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - "3309:3306"
    volumes:
      - shard2-data:/var/lib/mysql

  proxysql:
    image: proxysql/proxysql:3.0.1
    depends_on:
      - shard0
      - shard1
      - shard2
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf:ro
    ports:
      - "6033:6033"   # MySQL port
      - "6032:6032"   # admin port

volumes:
  shard0-data:
  shard1-data:
  shard2-data:
